# Generated by Django 4.2.1 on 2023-07-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text_of_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
