# Generated by Django 4.2.1 on 2023-07-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_comment_text_of_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_of_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
