# Generated by Django 4.2.1 on 2023-07-08 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_comment_comment_alter_comment_text_of_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text_of_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
